### ISSUE TITLE
Error adding OpenBabel to a node.js app in visual studio 2015

### ISSUE THREAD

**Issue by ch-hristov** [mohebifar/openbabel-node#4]
Using the npm inside node js tools for visual studio installing outputs :

Registry url: https://registry.npmjs.org/
Current Time: 30.8.2015 г. 1:58:52
Last Refreshed: 10.6.2015 г. 1:39:37
Number of Results: 164766
====Executing command 'npm install openbabel --save '====

npm WARN package.json NodejsConsoleApp2@0.0.0 No repository field.

> openbabel@1.2.3 install c:\users\hristo\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\openbabel
> node-gyp rebuild
> c:\users\hristo\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\openbabel>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [c:\users\hristo\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\openbabel\build\openbabel.vcxproj]
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd c:\users\hristo\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\openbabel
> gyp ERR! node -v v0.12.2
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "openbabel" "--save"
> npm ERR! node v0.12.2
> npm ERR! npm  v2.7.4
> npm ERR! code ELIFECYCLE
> npm ERR! openbabel@1.2.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the openbabel@1.2.3 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the openbabel package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls openbabel
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\users\hristo\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\npm-debug.log

====npm command completed with exit code 1====

**Comment by mohebifar** [comment]
Compiling with MS Visual Studio is not supported yet as I do not have any windows machine to set up node gyp configurations for that. Any PR would be appreciated.
