### ISSUE TITLE
error configure in ubuntu system

### ISSUE THREAD

**Issue by pincher-chen** [mohebifar/openbabel-node#5]
$ npm install openbabel -g
/

> openbabel@1.2.3 install /home/register/sf_install/node/lib/node_modules/openbabel
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/register/sf_install/node/lib/node_modules/openbabel/build'
  CXX(target) Release/obj.target/openbabel/src/atom.o
In file included from ../src/atom.cpp:1:0:
/home/register/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object, T = v8::Object]’:
/home/register/.node-gyp/0.12.0/deps/v8/include/v8.h:592:5:   instantiated from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Object, M = v8::NonCopyablePersistentTraits<v8::Object>, T = v8::Object, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Object>]’
/home/register/.node-gyp/0.12.0/deps/v8/include/v8.h:5826:3:   instantiated from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Object, M2 = v8::NonCopyablePersistentTraits<v8::Object>, T = v8::Object, M = v8::NonCopyablePersistentTraits<v8::Object>]’
/home/register/.node-gyp/0.12.0/deps/v8/include/v8.h:657:5:   instantiated from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Object, M = v8::NonCopyablePersistentTraits<v8::Object>, v8::Persistent<T, M> = v8::Persistent<v8::Object>]’
../src/atom.cpp:90:46:   instantiated from here
/home/register/.node-gyp/0.12.0/deps/v8/include/v8.h:596:5: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
make: *** [Release/obj.target/openbabel/src/atom.o] Error 1
make: Leaving directory`/home/register/sf_install/node/lib/node_modules/openbabel/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/register/sf_install/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.5.0-23-generic
gyp ERR! command "node" "/home/register/sf_install/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/register/sf_install/node/lib/node_modules/openbabel
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "/home/register/sf_install/node/bin/node" "/home/register/sf_install/node/bin/npm" "install" "openbabel" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! openbabel@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openbabel@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openbabel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openbabel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/register/sf_install/node/lib/node_modules/npm/npm-debug.log

How can i fix my mistakes?

**Comment by mohebifar** [comment]
This repo is pretty old and it makes me doubt what the issue actually is. I might update it in a few months but I can't tell you when. However, PRs are welcome at any point!
